# Generated by Django 4.1.3 on 2022-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super usuario')),
                ('username', models.CharField(max_length=200, verbose_name='Usuario')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('email', models.CharField(max_length=250, verbose_name='Correo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['date_joined'],
            },
        ),
    ]
